name: Build APKs

on:
  workflow_dispatch:
  push:
    branches: [ '**' ]
    paths-ignore:
      - 'README.md'
      - 'fastlane/**'
      - 'assets/**'
      - '.github/**/*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

permissions:
  contents: write
  discussions: write

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        abi: [ 'arm64', 'armeabi', 'x86', 'x86_64', 'universal' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: on-success

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assemble${{ matrix.abi }}Release
        env:
          PULL_REQUEST: 'false'

      - name: Move APK
        run: |
          mkdir -p app/build/outputs/apk/${{ matrix.abi }}/release/out
          find app/build/outputs/apk/${{ matrix.abi }}/release/ -name "*.apk" | xargs -I{} mv {} app/build/outputs/apk/${{ matrix.abi }}/release/out/app-${{ matrix.abi }}-release.apk
  
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.abi }}-release
          path: app/build/outputs/apk/${{ matrix.abi }}/release/out/*

  build_debug:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: on-success

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleUniversalDebug
        env:
          PULL_REQUEST: 'false'

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-universal-debug
          path: app/build/outputs/apk/universal/debug/*.apk