name: Build PR

on:
  pull_request:
    branches: ["**"]

jobs:
  build_debug:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: "on-success"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK (Universal)
        run: ./gradlew assembleUniversalDebug
        env:
          PULL_REQUEST: "true"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: universal-debug-apk
          path: app/build/outputs/apk/universal/debug/*.apk

  build_release:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: "on-success"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK (Universal)
        run: ./gradlew assembleUniversalRelease
        env:
          PULL_REQUEST: "true"

      - name: Move Release APK
        run: |
          mkdir -p app/build/outputs/apk/universal/release/out
          find app/build/outputs/apk/universal/release/ -name "*.apk" | xargs -I{} mv {} app/build/outputs/apk/universal/release/out/app-universal-release.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: universal-release-apk
          path: app/build/outputs/apk/universal/release/out/*.apk